### PR TITLE
Added loading circle when searching for certain client #223

### LINKED ISSUE #221: Show spinner when loading client via search bar
Steps to reproduce:

1. Navigate to http://localhost:5080/auth/clients
2. Type something in the search bar (top right of the screen) and press enter

Actual: The table refreshes after a couple of seconds without showing the Spinner component
Expected: The spinner component is displayed  while new data is being fetched

### PR DESCRIPTION
**Pull request by sammysamx20**
Fixes #221. 
The circle loads by rendering another Spinner component while the search is querying for results.

### CODE REVIEW

**Comment by sammysamx20** [comment]
It seems that my checks have failed. Do you know why this is? @helfi92

**Comment by sammysamx20** [comment]
@helfi92 I think the changes were made, let me know if there are still errors! Sorry this is my first time.

**Comment by sammysamx20** [comment]
@helfi92 I added the changes and on my original file it shows that there is no new line at the bottom. But the problem seems to persist on github and I'm not sure why?

**Comment by helfi92** [comment]
Can you try on a different editor perhaps?

**Comment by sammysamx20** [comment]
@helfi92 I think it should be changed now.

**Pull request merged**
