### PR TITLE
#247 - Changed the color of icons in logviewer light theme to match the dark theme

### PR DESCRIPTION
**Pull request by robbykim**
**Before:**
screen shot 2018-10-31 at 5 46 17 pm
**After:**
screen shot 2018-10-31 at 5 56 13 pm

### CODE REVIEW

**Comment by robbykim** [comment]
https://github.com/taskcluster/taskcluster-web/issues/247#issue-375691154

**Comment by helfi92** [comment]
@robbykim Let me know if there's anything unclear from my earlier comment :)

**Comment by helfi92** [comment]
I can take care of it, no worries.

**Comment by helfi92** [comment]
Fixed in https://github.com/taskcluster/taskcluster-web/commit/283fa16a54ea370574d9f6510165d52582a16242.

**Comment by robbykim** [comment]
@helfi92 Ahh, I'm so sorry, I didn't see your comments until now. Not sure why github wasn't emailing me notifications. Glad it was taken care of!

**Pull request closed without merging**
