### PR TITLE
Moving Task and LiveTask buttons to bottom right and adding extra lines

### LINKED ISSUE #401: In small logs, top-right buttons can obscure text
**Summary:**
[Example log](https://taskcluster-web.netlify.com/tasks/Zq9m4s9qQsqFYPfVMYJkkw/runs/9/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FZq9m4s9qQsqFYPfVMYJkkw%2Fruns%2F9%2Fartifacts%2Fpublic%2Flogs%2Flive_backing.log) (what's the text after `signing_task_schema`?). In cases where the log can't scroll, the buttons in the top-right obscure text. The only workaround is to view the raw log, which isn't ideal.

### PR DESCRIPTION
**Pull request by varundey**
Moving `Raw log`, `Go to line` and `View task` buttons of Task and LiveTask page to bottom right and adding two extra lines at the bottom of Task page. 
screen shot 2019-01-21 at 12 29 41 am

Fixes #401

### CODE REVIEW

**Comment by varundey** [comment]
The changes seems to be big and out of scope. Do you mind creating a separate issue for the changes? I would be glad to work on that. Let me know if you want me to make changes in this PR itself.

**Comment by varundey** [comment]
Any branch/commit where these changes are in place?

**Comment by helfi92** [comment]
> Any branch/commit where these changes are in place?

I'm not sure I understand the question. Could you elaborate, please?

**Comment by varundey** [comment]
I meant to ask if there's any branch which contains your review changes
against which I can compare the diff of my changes. Btw I think I screwed
up remote in my local git repo and thus the commit has unwanted changes.
Will push another commit in some time.

**Comment by varundey** [comment]
Moving over to #407

**Pull request closed without merging**
