### PR TITLE
Issue #124 Logging in/out should refetch queries

### PR DESCRIPTION
**Pull request by mike44441**
These changes will refetch the queries when the user signs in or out. The changes will only apply when the user signs out from the dashboard and when the user would sign into the website from either the initial start or while navigating. The site will not refresh when the user cancels from the credentials and only applies when they successfully log in.

### CODE REVIEW

**Comment by djmitche** [comment]
Hi @mike44441 - I'm curious if you're making this contribution as part of an Outreachy application?  If so, please remember to include the contribution on your application at outreachy.org!

**Comment by mike44441** [comment]
Hey @djmitche, I am doing these issues as a part of my coursework and also because I want to participate in open source projects to get more experience.

**Comment by djmitche** [comment]
Got it -- that's great!  Let @helfi92 or me know if we can be helpful!

**Comment by mike44441** [comment]
Awesome! Thanks, hope that this fixes the issue

**Comment by mike44441** [comment]
Alright I'll do that right now, would you want me to leave the comments or remove them?

**Comment by helfi92** [comment]
You can leave the comments to make it more readable :)

**Comment by mike44441** [comment]
I just pushed with the changes requested. =)

**Comment by helfi92** [comment]
@mike44441 https://github.com/taskcluster/taskcluster-web/issues/158 might be of interest to you. I can provide help as always :) Let me know if you're interested.

**Pull request merged**
